version: '3.8'

services:
  llmops-watcher:
    build: .
    container_name: llmops-watcher
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ${PWD}/prompts:/app/prompts
      - ${PWD}/testing_data:/app/testing_data
      - ${PWD}/best_prompt:/app/best_prompt
      - ${PWD}/best_model:/app/best_model
      - ${PWD}/configs:/app/configs
      - ${PWD}/logs:/app/logs
    command: python main.py
    # NO privileged: true or user/group settings here
