FROM python:3.10-slim

WORKDIR /app

COPY . /app

# Create required folders at image build time
RUN mkdir -p \
    /app/testing_data \
    /app/prompts \
    /app/configs \
    /app/logs \
    /app/best_model \
    /app/best_prompt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
