FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/best_model /app/best_prompt /app/logs

ENV PYTHONUNBUFFERED=1

