global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  # Core orchestration services
  - job_name: orchestrator
    static_configs: [{ targets: ["orchestrator:8000"]}]
    metrics_path: /metrics
    scrape_interval: 2s

  # - job_name: api_gateway
  #   static_configs: [{ targets: ["api-gateway:8080"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 10s

  # RAG and knowledge services
  # - job_name: rag_service
  #   static_configs: [{ targets: ["rag:8100"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 15s

  # - job_name: ingestion_curator
  #   static_configs: [{ targets: ["ingestion:8300"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 30s

  # Registry services
  # - job_name: prompt_registry
  #   static_configs: [{ targets: ["prompt-registry:8181"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 15s

  # - job_name: model_registry
  #   static_configs: [{ targets: ["model_registry:8501"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 15s

  # Governance and evaluation
  # - job_name: governance_gateway
  #   static_configs: [{ targets: ["localhost:8200"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 15s

  # - job_name: evaluator
  #   static_configs: [{ targets: ["localhost:8500"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 30s

  # MLflow tracking server
  - job_name: mlflow
    static_configs: [{ targets: ["mlflow:5000"] }]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: evaluation
    static_configs: [{ targets: ["evaluation:8111"] }]
    metrics_path: /metrics
    scrape_interval: 2s

  # Infrastructure services
  - job_name: prometheus
    static_configs: [{ targets: ["mlflow:9090"] }]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: grafana
    static_configs: [{ targets: ["grafana:3000"] }]
    metrics_path: /metrics
    scrape_interval: 5s

  # MySQL database
  # - job_name: mysql
  #   static_configs: [{ targets: ["mysql:3306"] }]
  #   metrics_path: /metrics
  #   scrape_interval: 30s

  # Prompt registry hits
  # - job_name: prompt_registry_hits
  #   static_configs:
  #     - targets: ["prompt-registry:8181"]
  #   metrics_path: /metrics
  #   scrape_interval: 10s
