
models:
  - llama-3.3-70b-versatile
  - mistral-saba-24b
  - deepseek-r1-distill-llama-70b


files:
  test_data: /app/testing_data/prompts.csv
  prompt_dir: /app/prompts/
  results_output: /app/results/eval_results.jsonl
  best_prompt_dir: /app/best_prompt/
  best_model_file: /app/best_model/model.txt

watch_dirs:
  - /app/configs/
  - /app/prompts/
  - /app/testing_data/



