# ===========================
# Governance Policy Config
# ===========================

# ---- PII Detection ----
pii_patterns:
  # Emails
  - "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"
  # Phone numbers (10-15 digits, allow +)
  - "\\+?\\d{10,15}"
  # Credit card numbers (13-16 digits)
  - "\\b(?:\\d[ -]*?){13,16}\\b"
  # Social Security Number (SSN)
  - "\\b\\d{3}-\\d{2}-\\d{4}\\b"
  # IP Address
  - "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"

pii_action: "redact"   # Options: redact | block | allow

# ---- Red Team / Jailbreak Checks ----
red_team_checks:
  jailbreak_words:
    - "ignore previous instructions"
    - "disregard your training"
    - "pretend you are not an AI"
    - "bypass safety"
    - "disable filter"
    - "system override"
    - "do anything now"

# ---- Toxicity Control ----
toxicity_threshold: 0.75   # 0.0–1.0, above this → block
toxicity_action: "block"   # Options: block | warn | escalate

# ---- Topic Restrictions ----
blocked_topics:
  - "terrorism"
  - "self-harm"
  - "weapons manufacturing"
  - "illegal drugs"
  - "child exploitation"

# ---- Escalation Settings ----
escalation:
  enabled: true
  notify_email: "safety-team@example.com"
  mode: "manual_review"   # manual_review | auto_redact

# ---- Logging / Audit ----
logging:
  mlflow_enabled: true
  prometheus_enabled: true
  redact_artifacts: true   # store redacted outputs instead of raw
